### ISSUE TITLE
apt-cyg install issues - Cygwin 3.1.2

### ISSUE THREAD

**Issue by userdocs** [kou1okada/apt-cyg#63] opened 2019-12-28 23:35 UTC
I am seeing this whenever attempting to install a program.

~~~
$ apt-cyg install lftp
iconv: conversion from CP20127 unsupported
iconv: try 'iconv -l' to get the list of supported encodings
iconv: conversion from CP20127 unsupported
iconv: try 'iconv -l' to get the list of supported encodings
cygpath: can't convert empty path
Cache directory is
Mirror is
iconv: conversion from CP20127 unsupported
iconv: try 'iconv -l' to get the list of supported encodings
Updating setup.ini
/x86_64/setup.bz2: Scheme missing.
/x86_64/setup.ini: Scheme missing.
Error: updating setup.ini failed, reverting.
at : /usr/local/bin/apt-cyg: setupini_download: 546

Installing lftp
awk: cmd. line:1: fatal: cannot open file `setup.ini' for reading (No such file or directory)
Found package lftp
Could not find "install" in package description: obsolete package?
~~~

**Comment by kou1okada** [comment] 2019-12-29 13:54
Hmm,,,
* [Code Page Identifiers](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers)

`CP20127` seems to be `US-ASCII`, but ...
```
$ iconv -l | grep 20127
$ iconv -l | grep -i us-ascii
ANSI_X3.4-1968 ANSI_X3.4-1986 ASCII CP367 IBM367 ISO-IR-6 ISO646-US ISO646.1991-IRV ISO_646.IRV:1991 US US-ASCII CSASCII
```
Oops, `iconv` can recognize `US-ASCII`, however, it can not recognize `CP20127`.

**Comment by kou1okada** [comment] 2019-12-29 14:03
I made a patch for resolving this issue on pull request #64.
Can you try it and review it?

**Comment by userdocs** [comment] 2019-12-29 14:18
I used the patch and it fixed issue i was experiencing. Thanks.

The only thing i see is this (which i am not sure is related or an issue)

![2019-12-29_14-15-29](https://user-images.githubusercontent.com/16525024/71557980-e7e6e400-2a45-11ea-9322-eb7103c0da95.png)

It looks like this symbol is an encoded `/` - is it meant to do this or install that folder to the root dir?

**Comment by userdocs** [comment] 2019-12-29 14:23
To add a clarification. That folder was not created after i installed your patch. Only before. I guess it was related. It all goes into `.pkg-cache` now. I tested it.

**Comment by kou1okada** [comment] 2019-12-29 18:14
Maybe `%2f` was made by missing Code Page.
But, `.pkg-cache` ?????
I can't remember that I made it.

**Comment by userdocs** [comment] 2019-12-29 18:25
I use this https://vegardit.github.io/cygwin-portable-installer/

I think it's part of the configuration.

**Comment by kou1okada** [comment] 2019-12-29 19:02
Is there any directory which name beginning with "http%3a%2f%2"?

**Comment by userdocs** [comment] 2019-12-29 19:56
Yes, it inside the `.pkg-cache` directory which in my Cygwin Root `system`.  System is  `/` to my portable Cygwin installation.

![2019-12-29_19-54-13](https://user-images.githubusercontent.com/16525024/71561921-129c6100-2a75-11ea-8865-36d58f10881b.png)

**Comment by userdocs** [comment] 2020-01-15 20:47
any update on merging this fix?

**Comment by kou1okada** [comment] 2020-02-05 02:20
Pull request #64 is merged, now.

**Closed by kou1okada** 2020-02-05 02:20 UTC

**Comment by darklie** [comment] 2020-02-17 07:13
I am seeing like this and "%2f" directory appears too.

> $ apt-cyg update
> /usr/local/bin/apt-cyg: line 396: : command not found
> iconv: conversion from -t unsupported
> iconv: try 'iconv -l' to get the list of supported encodings
> /usr/local/bin/apt-cyg: line 396: : command not found
> iconv: conversion from -t unsupported
> iconv: try 'iconv -l' to get the list of supported encodings
> cygpath: can't convert empty path
> Cache directory is
> Mirror is
> /usr/local/bin/apt-cyg: line 396: : command not found
> iconv: conversion from -t unsupported
> iconv: try 'iconv -l' to get the list of supported encodings
> Updating setup.ini
> /x86_64/setup.bz2: Scheme missing.
> /x86_64/setup.ini: Scheme missing.
> Error: updating setup.ini failed, reverting.
> at : /usr/local/bin/apt-cyg: setupini_download: 546

**Comment by kou1okada** [comment] 2020-02-17 10:21
Are you using https://vegardit.github.io/cygwin-portable-installer/ too?

Please report results of following commands:
```bash
{
  echo "=========="
  echo "# declare"
  declare -p COMSPEC SYSTEMROOT WINDIR PATH
  echo "# VER"
  apt-cyg call comspec /c VER
  echo "# WHERE chcp"
  apt-cyg call comspec /c WHERE chcp.com
  echo "# type chcp.com"
  type chcp.com
  echo "# ls chcp"
  type -p chcp.com | sed -E 's:(.*/).*:\1:g' | xargs ls -l | grep -i chcp
  echo "=========="
}
```

**Comment by darklie** [comment] 2020-03-10 02:08
I haven't using portable installer unlike Userdocs.
The command result's is here.
```
 ==========
# declare
/cygdrive/t/a.txt: line 4: declare: COMSPEC: not found
declare -x SYSTEMROOT="C:\\Windows"
declare -x WINDIR="C:\\Windows"
: not found/a.txt: line 4: declare: PATH
# VER
/usr/local/bin/apt-cyg: line 396: : command not found
# WHERE chcp
/usr/local/bin/apt-cyg: line 396: : command not found
# type chcp.com
: not found/a.txt: line 10: type: chcp.com
# ls chcp
==========
```

**Comment by kou1okada** [comment] 2020-03-10 02:49
Hmm, too bad.
The environment variables of `COMSPEC` and `PATH` are not declared in your environment.
The system, which does not have them, is abnormal.
Try to set them with the following commands:
```
export PATH="/bin:/usr/bin:/usr/local/bin:$WINDIR/System32"
export COMSPEC="$WINDIR/system32/cmd.exe"
```

I can not understand why they are not declared, but maybe it's caused by the portable installer that you used.
Which installer is it?
I can't give you any help without it.

Don't hide any information that you did on non-standard way, If you want supports.

**Comment by darklie** [comment] 2020-03-10 07:20
Installer is default https://cygwin.org/setup-86_64.exe.
I don't know why, but to boot cygwin from "Cygwin64 Terminal.lnk" on start menu, then happen this problem. However, to boot from Cygwin.bat on installed directory, then it doesn't happen.

I installed cygwin on "C:\tools\cygwin64\"

I would be grateful if you would solve this problem.

**Comment by kou1okada** [comment] 2020-03-10 09:12
> I have**n't** using portable installer unlike Userdocs.

Oops.
Sorry, I missed "n't".

Hmm, it's strange that mintty (`Cygwin64 Terminal.lnk`) failed but conhost (`Cygwin.bat`) succeed.
Can I check the result of the following commands:
```
{
  echo ==========
  echo "# comspec and path with declare -p"
  declare -p|grep -Ei ' (comspec|path)='
  echo
  echo "# comspec and path with declare"
  declare|grep -Ei '^(comspec|path)='
  echo
  echo "# environment variables in HKLM"
  ls "/proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Session Manager/Environment/"
  echo "ComSpec=$(cat "/proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Session Manager/Environment/ComSpec"|sed -E 's/\x00//g')"
  echo "Path=$(cat "/proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Session Manager/Environment/Path"|sed -E 's/\x00//g')"
  echo
  echo "# environment variables in HKCU"
  ls "/proc/registry/HKEY_CURRENT_USER/Environment/"
  echo "Path=$(cat "/proc/registry/HKEY_CURRENT_USER/Environment/Path"|sed -E 's/\x00//g')"
  echo "# root and Cygwin.bat"
  cygpath -aw /
  cat /Cygwin.bat
  echo "# Cygwin64 Terminal.link"
  "$WINDIR/system32/WindowsPowerShell/v1.0/powershell" -Command 'dir "$env:ProgramData/Microsoft/Windows/Start Menu/Programs/Cygwin/","$env:AppData/Microsoft/Windows/Start Menu/Programs/Cygwin/"'
  "$WINDIR/system32/WindowsPowerShell/v1.0/powershell" -Command 'dir "$env:ProgramData/Microsoft/Windows/Start Menu/Programs/Cygwin/Cygwin64 Terminal.lnk","$env:AppData/Microsoft/Windows/Start Menu/Programs/Cygwin/Cygwin64 Terminal.lnk"|foreach{(New-Object -ComObject WScript.Shell).CreateShortcut($_)}'
  echo ==========
} 
```

**Comment by darklie** [comment] 2020-03-11 06:24
through `cygwin64 Terminal.lnk`,
```
==========
# comspec and path with declare -p
declare -x PATH="/usr/local/bin:/usr/bin:/cygdrive/c/usr/local/bin:/cygdrive/c/tools/msys64/mingw64/bin:/cygdrive/c/Program Files (x86)/PDFtk/bin:/cygdrive/c/Program Files/PuTTY:/cygdrive/c/Program Files/TortoiseHg:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/TortoiseGit/bin:/cygdrive/c/Program Files (x86)/WinSCP:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/tools/php53:/cygdrive/c/Program Files/Java/jre6/bin:/cygdrive/c/Program Files/Java/jdk1.6.0_45/bin:/cygdrive/c/Program Files/CollabNet/Subversion Client:/cygdrive/d/Oracle/product/11.2.0/client_2:/cygdrive/d/Oracle/product/11.2.0/client_2/bin:/cygdrive/d/Oracle/product/11.2.0/client_1/bin:/cygdrive/c/tools/apache-maven-2.2.1/bin:/cygdrive/c/Program Files/TortoiseSVN/bin:/cygdrive/d/syngo.plaza/Program:/cygdrive/d/IBARS:/cygdrive/d/MegaOak/IBARS/spoolernetLib:/cygdrive/c/PROGRA~2/COMMON~1/Odbc/FILEMA~1:/cygdrive/c/Siemens/WebClient/Program:/cygdrive/c/tools/apache-maven-3.6.1/bin:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/90/Tools/binn"

# environment variables in HKLM
ESET_OPTIONS          PATHEXT                 SVN_SSH
FP_NO_HOST_CHECK      PERL5LIB                TEMP
GIT_SSH               PROCESSOR_ARCHITECTURE  TMP
JAVA_HOME             PROCESSOR_IDENTIFIER    USERNAME
JRE_HOME              PROCESSOR_LEVEL         windir
NLS_LANG              PROCESSOR_REVISION      windows_tracing_flags
NUMBER_OF_PROCESSORS  PSModulePath            windows_tracing_logfile
OS                    Path
cat: '/proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Session Manager/Environment/ComSpec': No such file or directory
ComSpec=
Path=C:\usr\local\bin;C:\tools\msys64\mingw64\bin;C:\Program Files (x86)\PDFtk\bin\;C:\Program Files\PuTTY\;C:\Program Files\TortoiseHg\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\WinSCP\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\php53;C:\Program Files\Java\jre6\bin;%JAVA_HOME%\bin\;C:\Program Files\CollabNet\Subversion Client;D:\Oracle\product\11.2.0\client_2;D:\Oracle\product\11.2.0\client_2\bin;D:\Oracle\product\11.2.0\client_1\bin;C:\tools\apache-maven-2.2.1\bin;C:\Program Files\TortoiseSVN\bin;D:\syngo.plaza\Program;D:\IBARS;D:\MegaOak\IBARS\spoolernetLib;C:\PROGRA~2\COMMON~1\Odbc\FILEMA~1;C:\Siemens\WebClient\Program;C:\tools\apache-maven-3.6.1\bin;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\

# environment variables in HKCU
PHP_PEAR_BIN_DIR   PHP_PEAR_INSTALL_DIR  PHP_PEAR_TEST_DIR
PHP_PEAR_DATA_DIR  PHP_PEAR_PHP_BIN      TEMP
PHP_PEAR_DOC_DIR   PHP_PEAR_SYSCONF_DIR  TMP
cat: /proc/registry/HKEY_CURRENT_USER/Environment/Path: No such file or directory
Path=

# root and Cygwin.bat
C:\tools\cygwin64

@echo off
setlocal enableextensions
set TERM=
cd /d "%~dp0bin" && .\bash --login -i

# Cygwin64 Terminal.link


    ディレクトリ: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Cygwin


Mode                LastWriteTime     Length Name                               
----                -------------     ------ ----                               
-a---        2019/11/11      9:13        705 Cygwin64 Terminal.lnk              
Get-ChildItem : パス 'C:\Users\GYOMU\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Cygwin\' が存在しないため検出できません。
発生場所 行:1 文字:4
+ dir <<<<  "$env:ProgramData/Microsoft/Windows/Start Menu/Programs/Cygwin/","$env:AppData/Microsoft/Windows/Start Menu/Programs/Cygwin/"
    + CategoryInfo          : ObjectNotFound: (C:\Users\GYOMU\...rograms\Cygwin\:String) [Get-ChildItem]、ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand





```
and don't end powershell process.

through `cygwin.bat`,
```
==========
# comspec and path with declare -p
declare -x COMSPEC="C:\\Windows\\system32\\cmd.exe"
declare -x PATH="/usr/local/bin:/usr/bin:/cygdrive/c/usr/local/bin:/cygdrive/c/tools/msys64/mingw64/bin:/cygdrive/c/Program Files (x86)/PDFtk/bin:/cyg
drive/c/Program Files/PuTTY:/cygdrive/c/Program Files/TortoiseHg:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/TortoiseGit/bin:/cygdrive
/c/Program Files (x86)/WinSCP:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsP
owerShell/v1.0:/cygdrive/c/tools/php53:/cygdrive/c/Program Files/Java/jre6/bin:/cygdrive/c/Program Files/Java/jdk1.6.0_45/bin:/cygdrive/c/Program File
s/CollabNet/Subversion Client:/cygdrive/d/Oracle/product/11.2.0/client_2:/cygdrive/d/Oracle/product/11.2.0/client_2/bin:/cygdrive/d/Oracle/product/11.
2.0/client_1/bin:/cygdrive/c/tools/apache-maven-2.2.1/bin:/cygdrive/c/Program Files/TortoiseSVN/bin:/cygdrive/d/syngo.plaza/Program:/cygdrive/d/IBARS:
/cygdrive/d/MegaOak/IBARS/spoolernetLib:/cygdrive/c/PROGRA~2/COMMON~1/Odbc/FILEMA~1:/cygdrive/c/Siemens/WebClient/Program:/cygdrive/c/tools/apache-mav
en-3.6.1/bin:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/90/Tools/binn"

# environment variables in HKLM
ESET_OPTIONS      JAVA_HOME  NUMBER_OF_PROCESSORS  PATHEXT                 PROCESSOR_IDENTIFIER  PSModulePath  TMP       windows_tracing_flags
FP_NO_HOST_CHECK  JRE_HOME   OS                    PERL5LIB                PROCESSOR_LEVEL       SVN_SSH       USERNAME  windows_tracing_logfile
GIT_SSH           NLS_LANG   Path                  PROCESSOR_ARCHITECTURE  PROCESSOR_REVISION    TEMP          windir
cat: '/proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Session Manager/Environment/ComSpec': No such file or directory
ComSpec=
Path=C:\usr\local\bin;C:\tools\msys64\mingw64\bin;C:\Program Files (x86)\PDFtk\bin\;C:\Program Files\PuTTY\;C:\Program Files\TortoiseHg\;C:\Program Fi
les\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\WinSCP\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System3
2\WindowsPowerShell\v1.0\;C:\tools\php53;C:\Program Files\Java\jre6\bin;%JAVA_HOME%\bin\;C:\Program Files\CollabNet\Subversion Client;D:\Oracle\produc
t\11.2.0\client_2;D:\Oracle\product\11.2.0\client_2\bin;D:\Oracle\product\11.2.0\client_1\bin;C:\tools\apache-maven-2.2.1\bin;C:\Program Files\Tortois
eSVN\bin;D:\syngo.plaza\Program;D:\IBARS;D:\MegaOak\IBARS\spoolernetLib;C:\PROGRA~2\COMMON~1\Odbc\FILEMA~1;C:\Siemens\WebClient\Program;C:\tools\apach
e-maven-3.6.1\bin;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\

# environment variables in HKCU
PHP_PEAR_BIN_DIR  PHP_PEAR_DATA_DIR  PHP_PEAR_DOC_DIR  PHP_PEAR_INSTALL_DIR  PHP_PEAR_PHP_BIN  PHP_PEAR_SYSCONF_DIR  PHP_PEAR_TEST_DIR  TEMP  TMP
cat: /proc/registry/HKEY_CURRENT_USER/Environment/Path: No such file or directory
Path=

# root and Cygwin.bat
C:\tools\cygwin64

@echo off
setlocal enableextensions
set TERM=
cd /d "%~dp0bin" && .\bash --login -i

# Cygwin64 Terminal.link


    ディレクトリ: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Cygwin


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        2019/11/11      9:13        705 Cygwin64 Terminal.lnk
Get-ChildItem : パス 'C:\Users\GYOMU\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Cygwin\' が存在しないため検出できません。
発生場所 行:1 文字:4
+ dir <<<<  "$env:ProgramData/Microsoft/Windows/Start Menu/Programs/Cygwin/","$env:AppData/Microsoft/Windows/Start Menu/Programs/Cygwin/"
    + CategoryInfo          : ObjectNotFound: (C:\Users\GYOMU\...rograms\Cygwin\:String) [Get-ChildItem]、ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand





FullName         : C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Cygwin\Cygwin64 Terminal.lnk
Arguments        : -i /Cygwin-Terminal.ico -
Description      :
Hotkey           :
IconLocation     : C:\tools\cygwin64\Cygwin-Terminal.ico,0
RelativePath     :
TargetPath       : C:\tools\cygwin64\bin\mintty.exe
WindowStyle      : 1
WorkingDirectory :

Get-ChildItem : パス 'C:\Users\GYOMU\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Cygwin\Cygwin64 Terminal.lnk' が存在しないため検出できませ
ん。
発生場所 行:1 文字:4
+ dir <<<<  "$env:ProgramData/Microsoft/Windows/Start Menu/Programs/Cygwin/Cygwin64 Terminal.lnk","$env:AppData/Microsoft/Windows/Start Menu/Programs
/Cygwin/Cygwin64 Terminal.lnk"|foreach{(New-Object -ComObject WScript.Shell).CreateShortcut($_)}
    + CategoryInfo          : ObjectNotFound: (C:\Users\GYOMU\...64 Terminal.lnk:String) [Get-ChildItem]、ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand



==========
```

**Comment by kou1okada** [comment] 2020-03-12 04:57
Your environment does not have $ComSpec in HKLM, so `Cygwin64 Terminal.lnk` does not have it too.
But `Cygwin.bat` has it.
It's too strange.
I can't understand where $ComSpec of `Cygwin.bat` came from.

Does the result of following command have $ComSpec?
```
"$WINDIR/system32/WindowsPowerShell/v1.0/powershell" -Command "Start-Process $WINDIR/system32/WindowsPowerShell/v1.0/powershell -Verb RunAs -ArgumentList \" -Command dir env:; pause\""
```

If the result of above command does not have it,  did you set it somewhere start up script?

I suggest to check the result of the following command:
```
grep -Ein 'comspec=' ~/.{profile,bash{rc,_profile,_login}} /etc/{bash.bashrc,profile}
```

On this result, if you find something about "comspec = ...", it's better to remove it, maybe.
Because it is not a standard setting.

As an alternative to it, you can recover the standard setting with the following command:
```
"$WINDIR/system32/WindowsPowerShell/v1.0/powershell" -Command "Start-Process $WINDIR/system32/WindowsPowerShell/v1.0/powershell -Verb RunAs -ArgumentList \" -Command reg ADD 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' /v ComSpec /t REG_EXPAND_SZ /d '%SystemRoot%\system32\cmd.exe'; pause\""
```
